### ISSUE TITLE
compiling issue with intel (_intel_fast_memcpy error)

### ISSUE THREAD

**Issue by mayankaditya** [SSCHAcode/CellConstructor#29]
Hi I have installed CellConstructor module with intel ( using setup-EB-intel-Python.py). I am getting this error while loading the modules.

**/hpc/home/mg422/.local/lib/python3.7/site-packages/cc_linalg.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcpy**

Thanks,
Mayank

**Comment by mesonepigreco** [comment]
Hi, this error seems to be due to the fact that you are compiling with the intel compiler but linking the library with a gnu compiler (cc_linalg.cpython-37m-x86_64-linux-gnu.so) that does not recognize some calls defined by the intel compiler (_intel_fast_memcpy).

You can manually specify the intel linker at compile time by calling:
LDSHARED=/path/to/intel-compiler python setup-EB-intel-Python.py

remember to remove the build directory before running the command above, otherwise the code will skip the compilation.
